---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Galaxy dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ galaxy_package_dependencies }}"

- name: Clone Galaxy into configured directory.
  git:
    repo: "{{ galaxy_repo }}"
    dest: "{{ galaxy_repo_dir }}"
    version: "{{ galaxy_version }}"
    update: "{{ galaxy_keep_updated }}"
    force: yes
    accept_hostkey: yes

- name: Fixed Galaxy template compose to use bridge pre-exist network.
  copy:
    src: compose.yml.j2
    dest: "{{galaxy_repo_dir}}/installer/roles/local_docker/templates/compose.yml.j2"

- include: galaxy-install-playbook.yml
  when: galaxy_run_install_playbook


